package cj

class Test18Interface {

    # interface Iface {
    #     def foo(self): String
    #     def bar(self, x: Int): Int
    # }

    # class Klass : Iface.Trait {
    #     def foo(self): String = "Klass.foo"
    #     def bar(self, x: Int): Int = x + x
    # }

    # @test
    # def iface() {
    #     {
    #         val iface: Iface = Klass()
    #         Assert.equal(iface.foo(), "Klass.foo")
    #         Assert.equal(iface.bar(24), 48)
    #     }
    # }
}
